name = "WhereIsMyDocstring"
uuid = "aac05064-a116-4aba-9bed-53c9d53f4642"
authors = ["Tommy Hofmann <thofma@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1.5"

[targets]
test = ["Test"]
